### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by StEvUgnIn** [lume/glas#109]
Prettier is good at formatting. But it leaves open for contributions and tests to be deployed without respecting project rules.

I propose to add and configure ESLint to include our project rules and add no-var-keyword rules and also ES5 rules about comma.

**Comment by trusktr** [comment]
Even without ESLint yet, we can add `prettier --check` to the test scripts at

https://github.com/lume/glas/blob/04a178b23788a79e4b4f88c55d9944dee1fff481/package.json#L12-L14

and it will be called by CI

https://github.com/lume/glas/blob/04a178b23788a79e4b4f88c55d9944dee1fff481/.github/workflows/nodejs.yml#L26

so PRs will fail if code isn't formatter.

In some other projects, I use ESLint + Prettier.

[Husky](https://www.npmjs.com/package/husky) + [lint-staged](https://www.npmjs.com/package/lint-staged) is great too.

It would be sweet to set up ESLint + Prettier (and any additional rules) along with Husky + lint-staged.

**Comment by trusktr** [comment]
All the other LUME packages use the same script, [for example](https://github.com/lume/element-behaviors/blob/74ac7a3fce839448fef4d24b804992afd17a5813/package.json#L16-L30), which come from [`@lume/cli`](https://github.com/lume/cli/).

Only lume/glas currently doesn't because it is so different, relying on `asc` and `as-pect`.

**Comment by ZoeDreams** [comment]
was working on implementing that, but need to support the cli to work on my windows machines. wip..

**Comment by trusktr** [comment]
will try to dig up the window machine tomorrow.

**Comment by StEvUgnIn** [comment]
Personally, I am more in inclined toward a ready-to-use solution instead of describing any linter configuration (`package.json` is universal for instance)... Deno comes with a formatter. If Visual Studio code is mandatory for contributing to the project, then we should write formatting rules inside VS code project configuration files.

**Comment by StEvUgnIn** [comment]
We could edit the gitignore as such: https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

**Comment by ZoeDreams** [comment]
You can configure checkstyle rules for github to enforce the lint and style rules., TODO; Commiting editor configurations is not practical. I generally only use Visual Studio Code to smoke test and code review. I use VIM, notepad++, and Sublime equally. I think its best to rely on our lint and prettier configurations. You can also adjust your VS Codes to match the project configuration so you can format the document and get the same results.

**Comment by ZoeDreams** [comment]
I think we should revisit 

> All the other LUME packages use the same scripts, [for example](https://github.com/lume/element-behaviors/blob/74ac7a3fce839448fef4d24b804992afd17a5813/package.json#L16-L30), which come from [`@lume/cli`](https://github.com/lume/cli/).
> 
> Only lume/glas currently doesn't because it is so different, relying on `asc` and `as-pect`.
> 
> But for stuff like ESLint and Prettier, it would be common in all the projects. It would be nice to add this to `lume/cli` and have all projects linted during their tests using the same commands from the cli.

also maybe create a some checkstyle unit tests / github action that does this. If the test fails then the PR wont be able to be merged.

**Comment by trusktr** [comment]
Yep. glas is the oddball of the LUME projects being so different (others are all regular TypeScript, this one is the only AssemblyScript one).

Yeah like Kara mentioned, some people don't use VS Code. The configs in the repo will be the source of truth, and every well-known IDE has Prettier/ESLint/EditorConfig/etc plugins to make it work in an editor of choice.

Been meaning to setup up commit checks with `lint-staged` and `husky` packages. Works really well: we can auto-format code on each commit, even if we're using only a plain text editor.



Got my Windows laptop ready now, so I'll be getting to testing it all in Windows soon. It should work in any OS (if we set up the the package.json scripts correctly).
