### ISSUE TITLE
wire up AS-to-JS function passing, write a unit test for it.

### ISSUE THREAD

**Issue by trusktr** [lume/glas#117]
Conversation is here: https://discord.com/channels/721472913886281818/721497900932137090/811322629755240528

Basically we need to make an abstraction for passing functions from AS to JS (maybe the other way too, but there's not a need for JS-to-AS right now).

Then we can implement `requestAnimationFrame`, `setTimeout`, etc, all callable inside AssemblyScript code.

**Comment by ZoeDreams** [comment]
working on this currently as part of the import-aswebglue

**Comment by trusktr** [comment]
We completed this in https://github.com/aspkg/ecmassembly
