### ISSUE TITLE
Should Use `asconfig.js` file instead of cli within `package.json`

### ISSUE THREAD

**Issue by ZoeDreams** [lume/glas#119]
This is a more maintainable way to create multiple compile time configurations. This will also allow us to more easily configure out table import and exports. see this [**page**](https://www.assemblyscript.org/compiler.html#command-line-options) for more information on the compiler options and implementation of the configuration file. Might also want to looking at implementing a dev and production build targets

**Comment by trusktr** [comment]
Nice! I don't think asconfig was around when we first started using AS. Or maybe I missed it. I always prefer config files as much as possible, leaving the minimal to the cli when needed.
