### ISSUE TITLE
Port Matrix4

### ISSUE THREAD

**Issue by trusktr** [lume/glas#28]

**Comment by jtenner** [comment]
Mind if I pitch in?

**Comment by trusktr** [comment]
@jtenner  Totally not! Hello!

There's plenty of classes to port. We're gonna move the classes here to GitHub issues instead of having them over in the [Google Doc](https://docs.google.com/document/d/1CojZ_Rry3a1rQnXf8KJcSiOGodTP905CVRsU-uiWQjo/edit).

I listed Matrix4 in particular, because I'm currently on this one. But this is the one with the weird numbers coming out in the matrix in the tests.

So the plan is to console.log the same parts of the Three.js tests and see how they diverge.

Meet us in https://gitter.im/infamous/glas for faster communication.

**Comment by trusktr** [comment]
When we add issues here for each class, let's assign them so we know who's working on what to avoid accidentally working on the same classes.

**Comment by trusktr** [comment]
@jtenner check out the `camera-classes-f32` or `camera-classes-f64` branches. When you run `npm install && npm test`, you'll see one test fail with the matrix output in console. 

Interestingly, on the f64 branch it is apparent that the precision from f64s throughout the code base gives us an extra decimal place of precision.

But the main problem (in either branch) is that the numbers in that failed test output match except one of them is negative. I wonder where that negative is coming from!

**Comment by jtenner** [comment]
Absolutely. I'll get around to this in about 6 hours.

**Comment by trusktr** [comment]
I think Matrix4 is done, now that the tests for camera classes are passing. Will merge that soon in https://github.com/lume/glas/pull/48
