### ISSUE TITLE
convert Math.sin/Math.cos into Math.sincos calls for 1.5 to 1.8x perf improvement

### ISSUE THREAD

**Issue by trusktr** [lume/glas#45]
(as per the AssemblyScript team)

We need to update AS first.

**Comment by StEvUgnIn** [comment]
Can you explain more about this task?

**Comment by kungfooman** [comment]
> Can you explain more about this task?

Example here: https://github.com/playcanvas/engine/pull/2213/commits/39631fbb6a62f90506f8c76c27655702fe28130b

Basically translate code like this:

```js
var sx = Mathf.sin(ex);
var cx = Mathf.cos(ex);
var sy = Mathf.sin(ey);
var cy = Mathf.cos(ey);
var sz = Mathf.sin(ez);
var cz = Mathf.cos(ez);
```

Into:

```js
Mathf.sincos(ex);
var sx = Mathf.sincos_sin;
var cx = Mathf.sincos_cos;
Mathf.sincos(ey);
var sy = Mathf.sincos_sin;
var cy = Mathf.sincos_cos;
Mathf.sincos(ez);
var sz = Mathf.sincos_sin;
var cz = Mathf.sincos_cos;
```

**Comment by StEvUgnIn** [comment]
But why though if not present in three.js and other project? In which way does it make the code more modular?

**Comment by kungfooman** [comment]
It's modularity vs performance vs a dozen of other concers, using my polyfill keeps your code still quite modular while increasing performance for the AS target. As much I know this project doesn't care about keeping AS code reusable in JS/TS anyway.

**Comment by StEvUgnIn** [comment]
Do you have some results that demonstrate this performance?

Does it use precompute the sine and the angle complement using the [Pythagorean trigonometric identity](https://en.wikipedia.org/wiki/Pythagorean_trigonometric_identity)?

**Comment by MaxGraey** [comment]
> Does it use precompute the sine and the angle complement using the Pythagorean trigonometric identity?

No, sincos just have shared argument range reduction stage (which is calc twice when call sin and cos separately). Also it shared other checks which much less impact in total perf boost.

**Comment by trusktr** [comment]
> As much I know this project doesn't care about keeping AS code reusable in JS/TS anyway.

Planning to compile to plain JS too, which will be helpful while the [WebGL HTML elements](https://codepen.io/trusktr/pen/oNzRKJN) are still in plain TS/JS.

**Comment by StEvUgnIn** [comment]
It doesn't work on my setup configuration (up to date)
https://gist.github.com/StEvUgnIn/2ba404abe92cab0ac432cc7ed7ac7fe1

**Comment by StEvUgnIn** [comment]
If anyone has any idea... I sought for sincos in Assemblyscript sources and I'm surprised it appears not to pass `asp` compilation

**Comment by trusktr** [comment]
I haven't seen any failed tests on `master` branch. But I also haven't checked that code yet. I'm sure once we try to render a graphic any error will show up.

**Comment by StEvUgnIn** [comment]
You shall close this topic. The work had been completed.

**Comment by trusktr** [comment]
> surprised it appears not to pass `asp` compilation

Oh ok. Wasn't sure what you meant by that.
